version: "3.7"

volumes:
    vue-cli-node-volume: 

services:
    todo:
        build:
            context: ./docker/web
        container_name: todo
        ports:
            - "8080:8080"
        volumes:
            - ./todo/:/app/
            - vue-cli-node-volume:/app/node_modules
        tty: true